aspecto-io/opentelemetry-ext-js

- packages/plugin-aws-sdk/package.json
- packages/plugin-aws-sdk/src/aws-sdk.ts
- packages/plugin-kafkajs/package.json
Plugins should not have peer dependency on the library they are instrumenting. It should have dev dependency only
> build: remove peer dependency from plugins

- .github/workflows/prerelease.yml
- package.json
[Monday issue](https://aspecto-io.monday.com/boards/312932205/pulses/1172560562)
In this pr I changed the preRelease github action. 
Prerelease versions will use the following format: 
`0.0.0-YYYY-MM-DD--hh-mm` for example: `0.0.0-2021-05-11--17-34`
> chore: fix prerelease github action

- packages/instrumentation-neo4j/package.json
- packages/instrumentation-neo4j/src/neo4j.ts
neo4j released a new version 4.3.0 where the internal files structure has changed and we need to take the right file when patching depending on the package version
https://aspecto-io.monday.com/boards/312932205/pulses/1341435063
> fix(instrumentation-neo4j): support neo4j driver >=4.3.0

- packages/instrumentation-sequelize/src/sequelize.ts
- packages/instrumentation-sequelize/test/sequelize.spec.ts
`Sequelize#query()` allows to omit second parameter. Instrumentation expects it to be present when getting the query type. This seems to be a typo as query options are expected to be nullable later in code.
Before the change any query without options will fail (e.g. Nest.js healthcheck [does so](https://github.com/nestjs/terminus/blob/f813fed40f065f747d5f9be65045296e5cc14aa8/lib/health-indicator/database/sequelize.health.ts#L79)).
> fix(instrumentation-sequelize): handle sequelize.query() call without options

- README.md
- detectors/node/resource-detector-deployment/package.json
- detectors/node/resource-detector-git/package.json
- detectors/node/resource-detector-service/package.json
- detectors/resource-detector-sync-api/package.json
- packages/instrumentation-amqplib/package.json
- packages/instrumentation-aws-sdk/package.json
- packages/instrumentation-elasticsearch/package.json
- packages/instrumentation-express/package.json
- packages/instrumentation-express/test/opentelemetry-express-layers.spec.ts
- packages/instrumentation-kafkajs/package.json
- packages/instrumentation-mongoose/package.json
- packages/instrumentation-neo4j/package.json
- packages/instrumentation-sequelize/package.json
- packages/instrumentation-socket.io/package.json
- packages/instrumentation-testing-utils/package.json
- packages/instrumentation-typeorm/package.json
- packages/propagation-utils/package.json
Upgrade to OpenTelemetry 0.22 which itself depends on `@opentelemetry/api` `1.0.0`
> chore: upgrade to opentelemetry 0.22.0

- detectors/node/resource-detector-deployment/package.json
- detectors/node/resource-detector-git/package.json
- detectors/node/resource-detector-service/package.json
- detectors/resource-detector-sync-api/package.json
- package.json
- packages/instrumentation-amqplib/package.json
- packages/instrumentation-amqplib/src/amqplib.ts
- packages/instrumentation-aws-sdk/package.json
- packages/instrumentation-aws-sdk/src/aws-sdk.ts
- packages/instrumentation-elasticsearch/package.json
- packages/instrumentation-elasticsearch/src/elasticsearch.ts
- packages/instrumentation-express/package.json
- packages/instrumentation-express/src/express.ts
- packages/instrumentation-kafkajs/package.json
- packages/instrumentation-kafkajs/src/kafkajs.ts
- packages/instrumentation-mongoose/package.json
- packages/instrumentation-mongoose/src/mongoose.ts
- packages/instrumentation-neo4j/package.json
- packages/instrumentation-neo4j/src/neo4j.ts
- packages/instrumentation-sequelize/package.json
- packages/instrumentation-sequelize/src/sequelize.ts
- packages/instrumentation-socket.io/package.json
- packages/instrumentation-socket.io/src/socket.io.ts
- packages/instrumentation-testing-utils/package.json
- packages/instrumentation-typeorm/package.json
- packages/instrumentation-typeorm/src/typeorm.ts
- packages/propagation-utils/package.json
- tsconfig.base.json
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/549
> chore: enable typescript 4.3 option noImplicitOverride

- packages/instrumentation-socket.io/test/socket.io.spec.ts
- packages/instrumentation-socket.io/test/utils.ts
The oldest current version supported is from 8 months ago. I'd like to support at least v2(2.0.0 released in 2017, latest 2.x in 2021). However, the initialization is a bit different for that. This PR prepares a few of the things without actually adding support for v2 or changing any of the behaviour to make the next PR more concise and easier to follow.
Check the commits for details, but:
* supports initialization in the way v2 does it - version checking is a bit hacky TBH, I'm open to a better way if you have any preferences;
* catches async errors in tests(stumbled upon those implementing v2 support);
* renames events "ping" and "pong" in tests since those are internally used for heartbeats in v2.
Look out for any linting/formatting inconsistencies, because I didn't find a way to …
> Prepare for v2 support

- packages/instrumentation-socket.io/.tav.yml
- packages/instrumentation-socket.io/README.md
- packages/instrumentation-socket.io/package.json
- packages/instrumentation-socket.io/src/socket.io.ts
- packages/instrumentation-socket.io/src/types.ts
- packages/instrumentation-socket.io/test/config.spec.ts
- packages/instrumentation-socket.io/test/socket.io.spec.ts
- packages/instrumentation-socket.io/test/utils.ts
This is currently WIP. And includes prep work from another PR(https://github.com/aspecto-io/opentelemetry-ext-js/pull/151). Test pass but there is
1. a race condition - Socket."emit is instrumented" test passes only because we don't wait for all the spans. There are async timers that are not cleaned up and process never terminates.
2. a problem with some internal state somewhere in Namespace tests - they pass beautifully if all the tests are ran together, but if only Namespace."on is instrumented" is ran, it fails with wrong number of spans created.
Should be easy enough fixes. The general theme should stay as it is right now so a preliminary review would also be nice! :wink:
EDIT
Solved the abovementioned issues and polished some last things. To reference points above:
1. Changed the …
> feat: add support for v2

- packages/instrumentation-aws-sdk/.tav.yml
- packages/instrumentation-aws-sdk/README.md
- packages/instrumentation-aws-sdk/src/aws-sdk.ts
- packages/instrumentation-aws-sdk/src/services/ServicesExtensions.ts
- packages/instrumentation-aws-sdk/src/services/sqs.ts
- packages/instrumentation-aws-sdk/src/utils.ts
- packages/instrumentation-aws-sdk/test/aws-sdk-v2.spec.ts
- packages/instrumentation-aws-sdk/test/aws-sdk-v3.spec.ts
- packages/instrumentation-aws-sdk/test/dynamodb.spec.ts
- packages/instrumentation-aws-sdk/test/sqs.spec.ts
Update the `opentelmetry-instrumentation-aws-sdk` package to follow the [common attributes in the specification for instrumentation of the AWS SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-sdk.md#common-attributes), specifically, this PR only address the issues with the "common attributes".
* `rpc.service` uses the unmodified `service.serviceIdentifier` instead of converting it to lower case
* `rpc.method` uses the unmodified `awsV2Request.operation` instead of converting it to CamelCase
Related to #160
> fix: Use AWS SDK Instrument spec for common attributes

- packages/instrumentation-aws-sdk/package.json
- packages/instrumentation-aws-sdk/src/services/dynamodb.ts
- packages/instrumentation-aws-sdk/test/dynamodb.spec.ts
PR adds additional attributes for the specific `DynamoDB` `BatchGetItem` command as defined in the specification for instrumentations of the AWS SDKs under the [specific DynamoDB - BatchGetItem](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-sdk.md#dynamodbbatchgetitem) subheading.
* Confirmed this works in both V3 and V2 by using the `normalized.commandInput` parameter
Blocked by #162
> feat: Add spec defined attributes for DynamoDB `BatchGetItem`

- packages/instrumentation-amqplib/src/amqplib.ts
Should allow dev to extend the publish and consume method to custom behavior. 
In more steps, should let user set the specific exchange or queue when creating class.
> feat: Allow extend function from external

- packages/instrumentation-elasticsearch/test/elastic.spec.ts
Fix tests for new version `7.14.0`.
Support [new product check](https://github.com/elastic/elasticsearch-js/pull/1487) request.
> fix: Elasticsearch v7.14.0 product check

- packages/instrumentation-amqplib/src/amqplib.ts
- packages/instrumentation-amqplib/src/types.ts
- packages/instrumentation-amqplib/test/amqplib-promise.spec.ts
Fixes #175 
This PR ignores falsely `msg`s, so they are not instrumented or traced, as they do not fit the current instrumentation specification.
In the future, we might want to add specific instrumentation for these messages with custom attributes and handling
> fix(instrumentation-amqplib): consumer cancel notification throws excption

- packages/instrumentation-amqplib/src/amqplib.ts
- packages/instrumentation-amqplib/src/types.ts
- packages/instrumentation-amqplib/src/utils.ts
- packages/instrumentation-amqplib/test/amqplib-callbacks.spec.ts
- packages/instrumentation-amqplib/test/amqplib-connection.spec.ts
- packages/instrumentation-amqplib/test/amqplib-promise.spec.ts
- packages/instrumentation-amqplib/test/config.ts
- packages/instrumentation-amqplib/test/utils.ts
Hi. This PR resolves https://github.com/aspecto-io/opentelemetry-ext-js/issues/84 with adding instrumentation to publish via ConfirmChannel of amqplib.
I am adding a new patch for confirm channel publish method which creates span in a similar way to normal channel publish. Span ends when the broker confirms the sent message (either ack or nack). If callback won't be fired (due to connection error or different protocol issue) the span will never end and there is no timeout implemented. 
It reassembles (afaik) a similar approach to unconfirmed messages callbacks of amqlib which shift out the whole callback array on channel error. Instrumentation is not storing the reference to these anywhere so it should be sufficient for eventual GC memory reclaim during channel close. 
Additionally, there …
> feat: amqp ConfirmChannel instrumentation

- packages/instrumentation-aws-sdk/src/aws-sdk.ts
exception is being thrown for trying to get serviceId on undefined clientConfig
> fix(aws-sdk): handle clientConfig undefined getting service id

- packages/instrumentation-sequelize/README.md
- packages/instrumentation-sequelize/src/sequelize.ts
- packages/instrumentation-sequelize/src/types.ts
- packages/instrumentation-sequelize/test/sequelize.spec.ts
Adds a new config `queryHook(span, { sql, option })` so that a span can be augmented with query details. The hook is run before the query is run.
Fixes #184
> feat: sequelize config queryHook

- packages/instrumentation-express/src/express.ts
Should fix express error: 
```
src/express.ts(226,13): error TS2322: Type '() => void' is not assignable to type '{ (cb?: () => void): Response<any>; (chunk: any, cb?: () => void): Response<any>; (chunk: any, encoding: BufferEncoding, cb?: () => void): Response<any>; }'.
Type 'void' is not assignable to type 'Response<any>'.
```
> fix(express): return original response

- packages/instrumentation-typeorm/test/config.spec.ts
TypeORM tests fail sometimes because of timeout error. It happen for test `TypeormInstrumentationConfig` -> `responseHook`. 
When the test pass successfully, it take more than 1.2 seconds.
In this PR I increased the timeout to 3 seconds.
> test(typeorm): increase test timeout

- packages/instrumentation-kafkajs/test/kafkajs.spec.ts
`heartbeat` function was added in the last `kafkajs` version `1.16.0`.
This PR should fix failing daily tests
> test(kafkajs): add missing heartbeat function

- packages/instrumentation-mongoose/src/utils.ts
Fix for: https://github.com/aspecto-io/opentelemetry-ext-js/issues/218
Re-orders the `span.end()` call so that it is called after the span is modified by the `applyResponseHook()` function.
> fix: re-order span.end() so that applyResponseHook affects emitted span

- README.md
- packages/instrumentation-elasticsearch/package.json
- packages/instrumentation-express/package.json
- packages/instrumentation-kafkajs/package.json
- packages/instrumentation-mongoose/package.json
- packages/instrumentation-neo4j/package.json
- packages/instrumentation-node-cache/package.json
- packages/instrumentation-sequelize/package.json
- packages/instrumentation-socket.io/package.json
- packages/instrumentation-typeorm/package.json
Hi, thanks for the amazing libs!
This PR updates the core experimental version to 0.32.0. I used [this PR](https://github.com/aspecto-io/opentelemetry-ext-js/pull/234) as a base for my work.
I had some problems running tests locally for the mongoose and neo4j instrumentations, it seems I need to configure those tools in my local environment. 
Edit: Found the comments in the tests about how to setup Docker for those instrumentations, all tests have passed.
I also had some problems with peer dependencies like:
```
opentelemetry-instrumentation-elasticsearch@0.29.0" has unmet peer dependency "@opentelemetry/api@^1.0.0".
```
I ignored these errors because they happened before I even started updating deps. I am probably missing something basic as I have little knowledge of Yarn in a lerna …
> feat: support core experimental version 0.32.0

- README.md
- packages/instrumentation-elasticsearch/package.json
- packages/instrumentation-express/package.json
- packages/instrumentation-kafkajs/package.json
- packages/instrumentation-mongoose/package.json
- packages/instrumentation-neo4j/package.json
- packages/instrumentation-node-cache/package.json
- packages/instrumentation-sequelize/package.json
- packages/instrumentation-socket.io/package.json
- packages/instrumentation-typeorm/package.json
Upgrade to latest `@opentelemetry/instrumentation` which has a peer dependency on `@opentelemetry/api@1.3.0`. `@opentelemetry/sdk-trace-base` in the dev deps had `@opentelemetry/api` pinned to `>= 1 <1.2.0` so I upgraded it to the latest version as well.
> feat: upgrade instrumentations to otel 0.34.0
